CREATE DATABASE IF NOT EXISTS demo
CREATE TABLE IF NOT EXISTS demo.template(`Id` String,`Message` String) ENGINE = MergeTree PRIMARY KEY Id ORDER BY Id SETTINGS index_granularity = 8192
CREATE TABLE IF NOT EXISTS demo.autorun AS demo.template
CREATE TABLE IF NOT EXISTS demo.app_sys_sec AS demo.template
CREATE TABLE IF NOT EXISTS demo.hardware_inventory AS demo.template
CREATE TABLE IF NOT EXISTS demo.tcpvcon2 AS demo.template
CREATE TABLE IF NOT EXISTS demo.winevent1 AS demo.template
CREATE TABLE IF NOT EXISTS demo.winevent3 AS demo.template
